"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-06 20:29:22.920777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_locks',
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('resource_type', 'resource_id')
    )
    op.create_index('idx_edit_locks_expires_at', 'edit_locks', ['expires_at'], unique=False)
    op.create_table('system_messages',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tag_preset_sections',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('columns', sa.Integer(), server_default='3', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('label', name='uq_tag_preset_sections_label')
    )
    op.create_index('idx_tag_preset_sections_sort', 'tag_preset_sections', ['sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('topic_card_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_media_message_ids', sa.JSON(), nullable=True),
    sa.Column('card_rendered_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('idx_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_table('tag_presets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('preset_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['preset_type'], ['tag_preset_sections.key'],
        name='fk_tag_presets_preset_type_tag_preset_sections', ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preset_type', 'label', name='uq_tag_presets_type_label'),
    sa.UniqueConstraint('preset_type', 'tag', name='uq_tag_presets_type_tag')
    )
    op.create_index('idx_tag_presets_type_sort', 'tag_presets', ['preset_type', 'sort_order'], unique=False)
    op.create_table('user_topics',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('current_status_key', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title_sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('title_applied_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('title_force_sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('topic_id'),
    sa.UniqueConstraint('topic_id', name='uq_user_topics_topic_id')
    )
    op.create_index('idx_user_topics_title_sync_pending', 'user_topics', ['updated_at'], unique=False, postgresql_where=sa.text('title_sync_version > title_applied_version'))
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_submission_id', 'messages', ['submission_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('edited_caption', sa.Text(), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel_message_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index('idx_publications_publish_at', 'publications', ['publish_at'], unique=False, postgresql_where='published_at IS NULL')
    op.create_index('idx_publications_submission_id', 'publications', ['submission_id'], unique=False)
    op.create_table('submission_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=512), nullable=False),
    sa.Column('file_unique_id', sa.String(length=256), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_media_submission_id', 'submission_media', ['submission_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the tag preset sections. tag_presets.preset_type is a FK onto this
    # table, so without at least one section the tag wizard has nothing to
    # write into. The sections themselves are editable from the bot; the
    # presets inside them are left empty on purpose.
    op.bulk_insert(
        sa.table(
            'tag_preset_sections',
            sa.column('key', sa.String()),
            sa.column('label', sa.String()),
            sa.column('columns', sa.Integer()),
            sa.column('sort_order', sa.Integer()),
        ),
        [
            {'key': 'category', 'label': 'Категории', 'columns': 1, 'sort_order': 1},
            {'key': 'setting', 'label': 'Места действия', 'columns': 3, 'sort_order': 2},
            {'key': 'character', 'label': 'Персонажи', 'columns': 3, 'sort_order': 3},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submission_media_submission_id', table_name='submission_media')
    op.drop_table('submission_media')
    op.drop_index('idx_publications_submission_id', table_name='publications')
    op.drop_index('idx_publications_publish_at', table_name='publications', postgresql_where='published_at IS NULL')
    op.drop_table('publications')
    op.drop_index('idx_messages_submission_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_user_topics_title_sync_pending', table_name='user_topics', postgresql_where=sa.text('title_sync_version > title_applied_version'))
    op.drop_table('user_topics')
    op.drop_index('idx_tag_presets_type_sort', table_name='tag_presets')
    op.drop_table('tag_presets')
    op.drop_index('idx_submissions_user_id', table_name='submissions')
    op.drop_index('idx_submissions_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('users')
    op.drop_index('idx_tag_preset_sections_sort', table_name='tag_preset_sections')
    op.drop_table('tag_preset_sections')
    op.drop_table('system_messages')
    op.drop_index('idx_edit_locks_expires_at', table_name='edit_locks')
    op.drop_table('edit_locks')
    # ### end Alembic commands ###
