"""moderator invites and role grant metadata

Adds the ``moderator_invites`` table for one-time deep-link invites, plus
``users.role_granted_by`` / ``users.role_granted_at`` recording who last
changed a user's role and when (both NULL for config-bootstrapped users).

Revision ID: 0003_moderator_invites
Revises: 0002_created_at_not_null
Create Date: 2026-08-07 02:12:03.556252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_moderator_invites'
down_revision: Union[str, None] = '0002_created_at_not_null'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_moderator_invites_expires_at', 'moderator_invites', ['expires_at'], unique=False)
    op.add_column('users', sa.Column('role_granted_by', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('role_granted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_users_role_granted_by_users', 'users', 'users', ['role_granted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_role_granted_by_users', 'users', type_='foreignkey')
    op.drop_column('users', 'role_granted_at')
    op.drop_column('users', 'role_granted_by')
    op.drop_index('idx_moderator_invites_expires_at', table_name='moderator_invites')
    op.drop_table('moderator_invites')
    # ### end Alembic commands ###
