"""Handler for Telegram service messages in the moderator forum group.

Suppresses system notifications generated by the Telegram API when forum topic
properties change (name, icon) or when a message is pinned. These messages are
noise in the moderation flow — the queue/schedule boards re-pin their messages
whenever a continuation chunk is created near a 30-entry boundary, which would
otherwise spam the group with "pinned a message" service messages.
"""

from aiogram import F, Router
from aiogram.exceptions import TelegramAPIError
from aiogram.types import Message, User
from sqlalchemy.ext.asyncio import AsyncSession

from core.config import config
from core.logging import get_logger
from db.queries import mark_topic_title_externally_drifted

logger = get_logger(__name__)

router = Router(name="service_messages")


def _fmt(user: User) -> str:
    name = user.full_name
    username = f" @{user.username}" if user.username else ""
    return f"id={user.id} ({name}{username})"


@router.message(F.new_chat_members)
async def _log_new_members(message: Message) -> None:
    if message.chat.id != config.moderator_group_id:
        return
    for user in message.new_chat_members or []:
        logger.info("Новый участник группы модераторов: %s", _fmt(user))


@router.message(F.forum_topic_created)
@router.message(F.forum_topic_closed)
@router.message(F.forum_topic_reopened)
@router.message(F.pinned_message)
async def _suppress_service_message(message: Message) -> None:
    """Delete a forum service message from the moderator group. Best-effort."""
    if message.chat.id != config.moderator_group_id:
        return
    try:
        await message.delete()
    except TelegramAPIError:
        logger.debug(
            "Не удалось удалить служебное сообщение %d в группе %d",
            message.message_id,
            message.chat.id,
        )


@router.message(F.forum_topic_edited)
async def _handle_topic_edited(
    message: Message,
    session: AsyncSession,
) -> None:
    """Queue repair for human renames, then suppress the service message."""
    if message.chat.id != config.moderator_group_id:
        return
    if (
        message.from_user is not None
        and not message.from_user.is_bot
        and message.message_thread_id is not None
    ):
        await mark_topic_title_externally_drifted(
            session, message.message_thread_id
        )
    await _suppress_service_message(message)
